### ISSUE TITLE
[FEATURE REQ] Support Java as language runtime in workshop path

### ISSUE THREAD

**Issue by pankajagrawal16** [Azure/aca-dotnet-workshop#33]
### Please describe the feature.

Add support for Java language as well. Idea is that same architecture will be created using Java as language runtime as well and attendees can follow either of the language path based on which language team is using today.

May be in future, this leaves us scope for adding additional runtime as well

**Comment by pankajagrawal16** [comment]
@tjoudeh @waelkdouh What do you think about this ?

**Comment by waelkdouh** [comment]
As the title suggests its a dotent focused workshop. There is another offering for Java specifically which you can find [here](https://azure.github.io/java-aks-aca-dapr-workshop/)
