### ISSUE TITLE
local mkdocs server serving at custom url

### ISSUE THREAD

**Issue by waelkdouh** [Azure/aca-dotnet-workshop#74]
### Please describe the feature.

Currently the mkdocs server being run from within the docker container is serving at  Serving on http://0.0.0.0:8000/. Any way that can be changes to serving on http://localhost:8000/. This way when folks click on the link it will take them to the correct url instead of asking the user to modify it in the browser.

![image](https://user-images.githubusercontent.com/10424576/233147284-40ea4aa6-a823-4328-96d8-035857fb7c1e.png)

**Comment by pankajagrawal16** [comment]
I dont think this is possible to change. There are several discussion around this as to why it is like this https://github.com/squidfunk/mkdocs-material/issues/238#issuecomment-367486396 and I have not found any way of solving it.

Probably not worth the effort as well? We should just accept the behavior I would say. What do you think? Should we close this issue? @waelkdouh
