### ISSUE TITLE
[FEATURE REQ] Support Workshop Application architecture for ACA Landing Zone

### ISSUE THREAD

**Issue by pankajagrawal16** [Azure/aca-dotnet-workshop#77]
### Please describe the feature.

Support for IAC sample to deploy application architecture in ACA Landing Zone accelerator 

https://github.com/Azure/aca-landing-zone-accelerator

**Comment by waelkdouh** [comment]
@pankajagrawal16 shiuodnwe mark this as completed?

**Comment by waelkdouh** [comment]
@pankajagrawal16 should we mark this as completed?

**Comment by pankajagrawal16** [comment]
Yes. This is done now. we should track adding it part of workshop content as seperate feature request.
