### ISSUE TITLE
Support VNET Integration

### ISSUE THREAD

**Issue by waelkdouh** [Azure/aca-dotnet-workshop#79]
Allow users to host the ACA cluster in a VNET behind an Application Gateway or Azure Front Door.

**Comment by pankajagrawal16** [comment]
I believe this will be mostly covered with deploying application in the ACA landing zone. Atleast using Application gateway bit is already covered in the PR which is raised, but we can look into adding support for front door as well.

Then we need to make the guidance part of the workshop content itself.
