### ISSUE TITLE
[BUG] Clarify port number update in automated deployment of app

### ISSUE THREAD

**Issue by hsirtl** [Azure/aca-dotnet-workshop#82]
### Describe the bug

In Module 10 it should state that, if someone (like me) followed along with the whole workshop and wants to use their own sourcecode, they would need to adjust the port numbers in the parameters file according to what they have in their Dockerfiles. Otherwise, the container apps would listen on port 80 and get into timeouts.

### Expected behavior

See bug description.

### Actual behavior

If you don't change port numbers, the container apps will get session timeouts in cases where the Dockerfile-builds make the containers listen on different ports.

### Reproduction Steps

See "Actual behavior".

**Comment by pankajagrawal16** [comment]
Hi @hsirtl  Thanks for opening the issue. I see it makes sense that we can clarify updating port number when following workshop since the start.

Would you like to contribute updating it? Happy to accept a PR and review. If not, I can look into fixing it later. Let me know.

**Comment by pankajagrawal16** [comment]
Changes are live now: https://azure.github.io/aca-dotnet-workshop/aca/10-aca-iac-bicep/iac-bicep/#deploy-the-infrastructure-and-create-the-components
