### ISSUE TITLE
Add contributor instructions to get workstation set up

### ISSUE THREAD

**Issue by simonkurtz-MSFT** [Azure/aca-dotnet-workshop#86]
### Please describe the feature.

I don't yet see a good way to get started as a contributor to the documentation. Whether this is a local setup via the makefile or using a dev container, it may be helpul to have instructions.

**Comment by pankajagrawal16** [comment]
But may be it should be less hidden in appendix

**Comment by simonkurtz-MSFT** [comment]
Oh, I see it now. Thank you! I think it would be valuable if we added a `CONTRIBUTING.MD` file in the repo's root since that's a standard file that users will look for. We can link to the appendix from there there.

**Comment by pankajagrawal16** [comment]
Makes sense. . Would you like to do that @simonkurtz-MSFT ?
